name: Contract CI

on:
  push:
    branches:
      - main
    paths:
      - "contract_/**"
  pull_request:
    paths:
      - "contract_/**"

defaults:
  run:
    working-directory: contract_

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    name: Cairo formatting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contract_/.tool-versions
      - name: Check Scarb Formatting
        run: scarb fmt --check

  compile:
    runs-on: ubuntu-latest
    name: Compile Cairo contract
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contract_/.tool-versions
      - name: Install universal sierra compiler
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh
          echo "/root/.local/bin" >> ${GITHUB_PATH}
      - name: Compile contract
        run: scarb build
      - name: Generate Starknet artifacts
        run: scarb sierra compile
      - name: Check contract size
        run: ls -la target/dev/
      - name: Upload compilation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contract-artifacts
          path: contract_/target/dev/

  run-test:
    runs-on: ubuntu-latest
    name: Cairo test
    needs: [compile]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: contract_/.tool-versions
      - name: Install universal sierra compiler
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh
          echo "/root/.local/bin" >> ${GITHUB_PATH}
      - name: Check universal sierra compiler version
        shell: bash
        run: universal-sierra-compiler --version
      # Rust is required by Starknet Foundry
      - name: Set Up Stable Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: contract_/.tool-versions
      - name: Run scarb test
        run: scarb test